import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import About from "../components/About";
import Contact from "../components/Contact";
import Footer from "../components/Footer/Footer";
import Form from "../components/Form";
import Header from "../components/Header/Header";
import Info from "../components/Info";
import Recruiting from "../components/Recruiting";
import Services from "../components/Services";
import Spinner from "../components/Spinner/Spinner";

export default function Home() {
  const router = useRouter();

  const [isLoading, setIsLoading] = useState<boolean>(false);

  const aboutRef = useRef();
  const servicesRef = useRef();
  const recruitingRef = useRef();
  const contactRef = useRef();

  interface Information {
    phone_number: string;
    email: string;
    address: string;
  }

  const information: Information = {
    phone_number: "+998 97 268 55 75",
    email: "info@argloballogistic.com",
    address: "Mirabad district, Kizil arvat str.2 passage house 37",
  };

  return (
    <>
      <Head>
        <title>AR Global - Logistic company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header
        aboutRef={aboutRef}
        servicesRef={servicesRef}
        recruitingRef={recruitingRef}
        contactRef={contactRef}
        setIsLoading={setIsLoading}
      />
      <main>
        <Info myRef={contactRef} />
        <About myRef={aboutRef} />
        <Services myRef={servicesRef} />
        <Recruiting myRef={recruitingRef} formRef={contactRef} />
        <Contact information={information} myRef={contactRef} />
        <Form />
      </main>
      <Footer />
      <Spinner isLoading={isLoading} setIsLoading={setIsLoading} />
    </>
  );
}
